In [1]:
from scripts import query

In [2]:
query.main()

=== INITIAL DATA EXPLORATION ===


--- First 10 Records ---
   world_rank                            institution         country  \
0           1                     Harvard University             USA
1           2  Massachusetts Institute of Technology             USA
2           3                    Stanford University             USA
3           4                University of Cambridge  United Kingdom
4           5     California Institute of Technology             USA
5           6                   Princeton University             USA
6           7                   University of Oxford  United Kingdom
7           8                        Yale University             USA
8           9                    Columbia University             USA
9          10     University of California, Berkeley             USA

   national_rank  quality_of_education  alumni_employment  quality_of_faculty  \
0              1                     7                  9                   1
1              2                     9                 17                   3
2              3                    17                 11                   5
3              1                    10                 24                   4
4              4                     2                 29                   7
5              5                     8                 14                   2
6              2                    13                 28                   9
7              6                    14                 31                  12
8              7                    23                 21                  10
9              8                    16                 52                   6

   publications  influence  citations broad_impact  patents   score  year
0             1          1          1                     5  100.00  2012
1            12          4          4                     1   91.67  2012
2             4          2          2                    15   89.50  2012
3            16         16         11                    50   86.17  2012
4            37         22         22                    18   85.21  2012
5            53         33         26                   101   82.50  2012
6            15         13         19                    26   82.34  2012
7            14          6         15                    66   79.14  2012
8            13         12         14                     5   78.86  2012
9             6          5          3                    16   78.55  2012

--- Universities in Multiple Years ---
                          institution  years_present
0            Arizona State University              4
1                   Boston University              4
2                    Brown University              4
3  California Institute of Technology              4
4          Carnegie Mellon University              4
5                 Columbia University              4
6                  Cornell University              4
7                   Dartmouth College              4
8                     Duke University              4
9                    Emory University              4

--- Average Rank per Country in 2015 ---
       country  avg_rank_2015
0    Singapore         100.00
1  Switzerland         120.71
2       Israel         126.60
3    Australia         161.13
4          USA         180.12
5        Japan         181.06
6      Denmark         181.50
7  Netherlands         189.92
8       France         198.47
9       Norway         208.33

--- Year-over-Year Change in Average Score ---
   year  avg_score  change_from_last_year
0  2012      54.94                    NaN
1  2013      55.27                   0.33
2  2014      47.29                  -7.99
3  2015      49.97                   2.69

=== CRUD OPERATIONS ===


=== INSERT OPERATION ===
Inserting Duke Tech (USA, 350, 60.5, 2014)...
Inserted row: [(350, 'Duke Tech', 'USA', None, None, None, None, None, None, None, None, None, 60.5, 2014), (350, 'Duke Tech', 'USA', None, None, None, None, None, None, None, None, None, 60.5, 2014)]

=== READ OPERATION ===
Counting Japan universities in top 200 in 2013...
Japan universities in top 200 in 2013: 6

=== UPDATE OPERATION ===
Updating University of Oxford 2014 score +1.2...
Before update: [('University of Oxford', 2014, 98.71000000000001)]
After update: [('University of Oxford', 2014, 99.91000000000001)]

=== DELETE OPERATION ===
Deleting 2015 universities with score < 45...
Deleted rows count (cumulative): 2
Remaining 2015 rows: 444

=== DONE ===